### Level 1 Tests - List all menus
GET http://localhost:3000/menus
Accept: application/json

### Show one menu
GET http://localhost:3000/menus/298486374
Accept: application/json

### Show all menu items
GET http://localhost:3000/menu_items
Accept: application/json

### Show one menu item
GET http://localhost:3000/menu_items/980190962
Accept: application/json


### Level 2 Tests - Create a restaurant
POST http://localhost:3000/restaurants
Accept: application/json
Content-Type: application/json

{
  "restaurant": {
    "name": "Poppo's Cafe"
  }
}

### List all restaurants
GET http://localhost:3000/restaurants
Accept: application/json

### Show a restaurant
GET http://localhost:3000/restaurants/1
Accept: application/json

### Update a restaurant
PUT http://localhost:3000/restaurants/1
Content-Type: application/json
Accept: application/json

{
  "restaurant": {
    "name": "Poppo's Café New Name"
  }
}

### Delete a restaurant
DELETE http://localhost:3000/restaurants/2
Accept: application/json